name: "Prometheus: The Documentary"
type: Documentary
category: Applications / Frameworks / Systems
links:
  youtube: https://www.youtube.com/watch?v=rT4fJNbfe14
tags:
  - Observability
  - Monitoring
  - Open Source
  - Cloud Native
  - History
